New patch to fix minor problem in examples that can break compilation:
Making install in examples
if gcc -DHAVE_CONFIG_H
-I. -I. -I.. -I/Users/jeffrey/Documents/cajun/rsl2mat/rsl/install/include
-g -MT kwaj_subtract_one_day.o -MD -MP -MF
".deps/kwaj_subtract_one_day.Tpo" -c -o kwaj_subtract_one_day.o
kwaj_subtract_one_day.c; \
    then mv -f ".deps/kwaj_subtract_one_day.Tpo"
    ".deps/kwaj_subtract_one_day.Po"; else rm -f
    ".deps/kwaj_subtract_one_day.Tpo"; exit 1; fi
kwaj_subtract_one_day.c:40:3: error: non-void function
'subtract_one_day' should return a value
      [-Wreturn-type]
  return;
  ^

The fix is to have the function return void instead of void *